import type { Product } from "../definitions";

export const products: Product[] = [
  {
    id: 1001,
    name: "סמסונג QLED 55 אינץ'",
    description:
      "טלוויזיית QLED חכמה עם רזולוציית 4K, צבעים מדהימים וחוויית צפייה משופרת. כוללת חיבור WiFi מובנה ותמיכה באפליקציות סטרימינג.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/n/e/new_project_samqe55q70datxsq.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/n/e/new_project_samsqe55q70datxsq.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/n/e/new_project_samqe55q70datxsq_1_.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/n/e/new_project_samqe55q70datxsq_2_.png",
    ],
    price: 3499,
    discount: 300,
    categories: ["televisions"],
    amount: 15,
    rating: 4.0,
    reviews: 7,
    specifications: {
      screen_size: "55 אינץ'",
      resolution: "4K Ultra HD",
      panel_type: "QLED",
      hdmi_ports: "3 יציאות",
      smart_features: "Tizen",
      bluetooth: "יש",
    },
  },
  {
    id: 1002,
    name: "LG OLED 65 אינץ'",
    description:
      "טלוויזיית OLED פרימיום עם איכות תמונה מושלמת, צבעים עשירים ושחור אמיתי. תמיכה ב-Dolby Vision IQ ו-Dolby Atmos לחוויית קולנוע ביתית.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/o/l/oled55b46la_1.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/o/l/oled55b46la_1__1.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/o/l/oled55b46la_3__1.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/o/l/oled55b46la_5__1.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/o/l/oled55b46la_4__1.png",
    ],
    price: 5999,
    discount: 500,
    categories: ["televisions"],
    amount: 8,
    rating: 4.9,
    reviews: 21,
    specifications: {
      screen_size: "65 אינץ'",
      resolution: "4K Ultra HD",
      panel_type: "OLED",
      hdmi_ports: "4 יציאות",
      smart_features: "webOS",
      bluetooth: "יש",
    },
  },
  {
    id: 1003,
    name: "סוני 4K 50 אינץ'",
    description:
      "טלוויזיית LED חכמה עם מעבד תמונה X1, רזולוציית 4K וטכנולוגיית TRILUMINOS לצבעים מדויקים. ממשק אנדרואיד TV נוח לשימוש.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/n/e/new_project_1220__7.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/n/e/new_project_1222__7.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/n/e/new_project_1223__7.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/n/e/new_project_1221__7.png",
    ],
    price: 2899,
    discount: 200,
    categories: ["televisions"],
    amount: 12,
    rating: 3.9,
    reviews: 8,
    specifications: {
      screen_size: "50 אינץ'",
      resolution: "4K Ultra HD",
      panel_type: "LED",
      hdmi_ports: "3 יציאות",
      smart_features: "Android TV",
      bluetooth: "יש",
    },
  },
  {
    id: 1004,
    name: "פיליפס אמבילייט 58 אינץ'",
    description:
      "טלוויזיית LED עם טכנולוגית Ambilight המקרינה אור מאחורי המסך בהתאם לתמונה. רזולוציית 4K ומעבד P5 לתמונה חדה ומציאותית.",
    images: [
      "https://www.dailysale.co.il/images/itempics/79732_201020231144141.jpg",
      "https://www.dailysale.co.il/images/itempics/79732_20102023114701.jpg",
    ],
    price: 3799,
    discount: 400,
    categories: ["televisions"],
    amount: 10,
    rating: 3.6,
    reviews: 15,
    specifications: {
      screen_size: "58 אינץ'",
      resolution: "4K Ultra HD",
      panel_type: "LED",
      hdmi_ports: "3 יציאות",
      smart_features: "Android TV",
      bluetooth: "יש",
    },
  },
  {
    id: 1005,
    name: "סמסונג The Frame 43 אינץ'",
    description:
      "טלוויזיה חכמה עם עיצוב ייחודי המחקה מסגרת תמונה. מצב אמנות מובנה להצגת יצירות אמנות כשהטלוויזיה במצב כבוי.",
    images: [
      "https://d3m9l0v76dty0.cloudfront.net/system/photos/12879993/extra_large/45e0eef2156bcf83f5c16f9e687649c0.png",
      "https://d3m9l0v76dty0.cloudfront.net/system/photos/12879994/extra_large/81c1a950953bcc83d981a81e78fd3240.png",
      "https://d3m9l0v76dty0.cloudfront.net/system/photos/12879995/extra_large/c90112f806763b8c3df33619a8090fe2.png",
      "https://d3m9l0v76dty0.cloudfront.net/system/photos/12879996/extra_large/2f238044c324d150175bb083756d4ba2.png",
    ],
    price: 4299,
    discount: 300,
    categories: ["televisions"],
    amount: 7,
    rating: 4.3,
    reviews: 19,
    specifications: {
      screen_size: "43 אינץ'",
      resolution: "4K Ultra HD",
      panel_type: "QLED",
      hdmi_ports: "4 יציאות",
      smart_features: "Tizen",
      bluetooth: "יש",
    },
  },
  {
    id: 1006,
    name: "TCL QLED 65 אינץ'",
    description:
      "טלוויזיית QLED במחיר משתלם עם רזולוציית 4K, תאורת Quantum Dot וטכנולוגיית HDR Premium. ממשק Google TV מובנה וחווית משתמש חלקה.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/c/6/c69b_1.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/c/6/c69b_3__1.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/c/6/c69b_4__1.png",
    ],
    price: 2999,
    discount: 400,
    categories: ["televisions"],
    amount: 14,
    rating: 3.8,
    reviews: 12,
    specifications: {
      screen_size: "65 אינץ'",
      resolution: "4K Ultra HD",
      panel_type: "QLED",
      hdmi_ports: "3 יציאות",
      smart_features: "Android TV",
      bluetooth: "יש",
    },
  },
  {
    id: 1007,
    name: "היסנס לייזר TV 100 אינץ'",
    description:
      "מקרן לייזר 4K עם טכנולוגיית תריסה קצרה המאפשרת הקרנה של עד 100 אינץ' ממרחק קצר מהקיר. כולל מסך הקרנה ייעודי וממשק חכם.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/n/e/new_hisense_u72kq.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/n/e/new_c__users_karin.baslo_downloads_2025-04-07_10_37_33-__100u72kq.pdf.png.png",
    ],
    price: 11999,
    discount: 1000,
    categories: ["televisions"],
    amount: 3,
    rating: 4.2,
    reviews: 5,
    specifications: {
      screen_size: "100 אינץ'",
      resolution: "4K Ultra HD",
      panel_type: "LED",
      hdmi_ports: "3 יציאות",
      smart_features: "Android TV",
      bluetooth: "יש",
    },
  },
  {
    id: 1008,
    name: "LG NanoCell 75 אינץ'",
    description:
      "טלוויזיית LED גדולה עם טכנולוגיית NanoCell לצבעים מדויקים, רזולוציית 4K ומעבד α7 Gen4. תמיכה ב-HDR10 Pro ו-HLG לתמונה דינמית.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/n/a/nano81t6a_3.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/n/a/nano81t6a_1__3.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/n/a/nano81t6a_3__3.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/n/e/new_proje50nano81t6a_ct_3.png",
    ],
    price: 6499,
    discount: 500,
    categories: ["televisions"],
    amount: 6,
    rating: 4.1,
    reviews: 14,
    specifications: {
      screen_size: "75 אינץ'",
      resolution: "4K Ultra HD",
      panel_type: "LED",
      hdmi_ports: "4 יציאות",
      smart_features: "webOS",
      bluetooth: "יש",
    },
  },
  {
    id: 1009,
    name: "סוני BRAVIA XR OLED 77 אינץ'",
    description:
      "טלוויזיית OLED פרימיום עם מעבד קוגניטיבי XR, רזולוציית 4K ותמיכה ב-120Hz. טכנולוגיית Acoustic Surface Audio+ לצליל יוצא מן הכלל.",
    images: [
      "https://www.pisga-shop.co.il/images/itempics/5841_07012024012539.jpg",
      "https://www.pisga-shop.co.il/images/itempics/5841_07012024012542.jpg",
      "https://www.pisga-shop.co.il/images/itempics/5841_07012024012552.jpg",
      "https://www.pisga-shop.co.il/images/itempics/5841_07012024012555.jpg",
    ],
    price: 14999,
    discount: 1500,
    categories: ["televisions"],
    amount: 2,
    rating: 4.8,
    reviews: 9,
    specifications: {
      screen_size: "77 אינץ'",
      resolution: "4K Ultra HD",
      panel_type: "OLED",
      hdmi_ports: "4 יציאות",
      smart_features: "Android TV",
      bluetooth: "יש",
    },
  },
  {
    id: 2001,
    name: "מקבוק פרו 14 אינץ'",
    description:
      "מחשב נייד Apple MacBook Pro עם שבב M2 Pro, זיכרון 16GB, אחסון 512GB SSD ומסך Liquid Retina XDR. ביצועים מהירים במיוחד ותצוגה מרהיבה.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/m/a/macbook_pro_14-in_space_black_pure_front_screen__usen_4.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/m/a/macbook_pro_14-inch_m4_chip_space_black_pdp_image_position_2__wwen_4.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/m/a/macbook_pro_14-in_space_black_pure_side_left_screen__usen_4.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/m/a/macbook_pro_14-in_space_black_pure_top_screen__usen_4.png",
    ],
    price: 7999,
    discount: 400,
    categories: ["computers"],
    amount: 10,
    rating: 4.7,
    reviews: 24,
    specifications: {
      processor: "Apple M2",
      ram: "16GB",
      storage: "512GB SSD",
      graphics_card: "Apple GPU",
      operating_system: "macOS",
      connectivity_ports: ["USB-C", "Thunderbolt"],
    },
  },
  {
    id: 2002,
    name: "דל XPS 15",
    description:
      "מחשב נייד עוצמתי עם מעבד Intel Core i7, כרטיס מסך NVIDIA GeForce RTX, מסך 15.6 אינץ' באיכות 4K ו-16GB RAM. מושלם לעבודה וגיימינג.",
    images: [
      "https://d3m9l0v76dty0.cloudfront.net/system/photos/12574570/extra_large/8e2ccad76acea510d5a170d4350eb3a3.jpg",
      "https://d3m9l0v76dty0.cloudfront.net/system/photos/12574571/extra_large/0c44232f4c58ebff1777737c2e544ab3.jpg",
      "https://d3m9l0v76dty0.cloudfront.net/system/photos/12574572/extra_large/16adab4dc2fa29d173ae55f36747a06b.jpg",
      "https://d3m9l0v76dty0.cloudfront.net/system/photos/12574574/extra_large/fdd4aa053b86ee2790071559812673b8.jpg",
    ],
    price: 6499,
    discount: 300,
    categories: ["computers"],
    amount: 7,
    rating: 4.3,
    reviews: 16,
    specifications: {
      processor: "Intel Core i7",
      ram: "16GB",
      storage: "512GB SSD",
      graphics_card: "NVIDIA GeForce RTX",
      operating_system: "Windows 11",
      connectivity_ports: ["USB-C", "USB 3.0", "HDMI"],
    },
  },
  {
    id: 2003,
    name: "מחשב נייח גיימינג ASUS ROG",
    description:
      "מחשב גיימינג עוצמתי עם מעבד AMD Ryzen 9, כרטיס מסך RTX 4080, 32GB RAM ו-2TB SSD. מושלם למשחקים ברזולוציה גבוהה ותוכנות כבדות.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/8/1/81475f62-0c10-42b4-b667-023c99a78ba5.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/0/7/07329593-0073-4039-b81d-a95c7d9f1cf6.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/b/3/b35fa183-a1c1-45fd-9315-3318180ba745.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/4/3/4336aca0-be28-4ea4-b0ae-a1b65e818397.png",
    ],
    price: 8999,
    discount: 600,
    categories: ["computers"],
    amount: 5,
    rating: 4.5,
    reviews: 13,
    specifications: {
      processor: "AMD Ryzen 9",
      ram: "32GB",
      storage: "2TB SSD",
      graphics_card: "NVIDIA GeForce RTX",
      operating_system: "Windows 11",
      connectivity_ports: ["USB-C", "USB 3.0", "HDMI", "DisplayPort"],
    },
  },
  {
    id: 2004,
    name: "מסך גיימינג LG 27 אינץ'",
    description:
      "מסך גיימינג 27 אינץ' עם קצב רענון 165Hz, זמן תגובה 1ms ותמיכה ב-G-SYNC. רזולוציית QHD לתמונה חדה וצבעים מדויקים.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/d/z/dz-1_1_1.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/d/z/dz-3_1_1.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/d/z/dz-5_1_1.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/d/z/dz-7_1.png",
    ],
    price: 1799,
    discount: 150,
    categories: ["computers", "accessories"],
    amount: 20,
    rating: 4.2,
    reviews: 18,
    specifications: {
      processor: null,
      ram: null,
      storage: null,
      graphics_card: null,
      operating_system: null,
      connectivity_ports: ["HDMI", "DisplayPort"],
      compatibility_accessory: "מחשבי Windows",
      material: "פלסטיק",
      connection_type: ["HDMI", "DisplayPort"],
      warranty: "שנתיים",
      color_options: "שחור",
      durability: "עמיד לשריטות",
    },
  },
  {
    id: 2005,
    name: "HP Spectre x360",
    description:
      "מחשב נייד 2 ב-1 עם מסך מגע 13.5 אינץ', מעבד Intel Core i7, 16GB RAM, 1TB SSD וסוללה שמספיקה ליום עבודה מלא. עיצוב יוקרתי ודק במיוחד.",
    images: [
      "https://m.media-amazon.com/images/I/71QYAmDIhfL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71AgpORJXXL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61wXBpe2jiL._AC_SL1500_.jpg",
    ],
    price: 5799,
    discount: 400,
    categories: ["computers"],
    amount: 12,
    rating: 4.1,
    reviews: 14,
    specifications: {
      processor: "Intel Core i7",
      ram: "16GB",
      storage: "1TB SSD",
      graphics_card: "משולב",
      operating_system: "Windows 11",
      connectivity_ports: ["USB-C", "USB 3.0", "HDMI"],
    },
  },
  {
    id: 2006,
    name: "לנובו ThinkPad X1 Carbon",
    description:
      "מחשב נייד עסקי עם מעבד Intel Core i5, 16GB RAM, 512GB SSD ומסך 14 אינץ' FHD+. עמיד במיוחד, קל משקל ועם חיי סוללה ארוכים.",
    images: [
      "https://www.espir.co.il/images/itempics/21KC004QIV_26092024150059_large.jpg",
      "https://www.espir.co.il/images/itempics/21KC004QIV_21042024161157_large.jpg",
      "https://www.espir.co.il/images/itempics/21KC004QIV_21042024161203_large.jpg",
    ],
    price: 4999,
    discount: 300,
    categories: ["computers"],
    amount: 15,
    rating: 4.0,
    reviews: 22,
    specifications: {
      processor: "Intel Core i5",
      ram: "16GB",
      storage: "512GB SSD",
      graphics_card: "משולב",
      operating_system: "Windows 11",
      connectivity_ports: ["USB-C", "USB 3.0", "HDMI", "Thunderbolt"],
    },
  },
  {
    id: 2007,
    name: "HP Pavilion All-in-One",
    description:
      "מחשב שולחני הכל-במסך עם מסך 27 אינץ' FHD, מעבד Intel Core i5, 8GB RAM ו-512GB SSD. מצלמה מובנית וממשק זיהוי פנים.",
    images: [
      "https://m.media-amazon.com/images/I/612FzPlgWxL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61WBBJ9Qx-L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51pIPtcSVpL._AC_SL1500_.jpg",
    ],
    price: 3999,
    discount: 300,
    categories: ["computers"],
    amount: 8,
    rating: 3.5,
    reviews: 10,
    specifications: {
      processor: "Intel Core i5",
      ram: "8GB",
      storage: "512GB SSD",
      graphics_card: "משולב",
      operating_system: "Windows 11",
      connectivity_ports: ["USB-C", "USB 3.0", "HDMI"],
    },
  },
  {
    id: 2008,
    name: "אסוס Zenbook 14",
    description:
      "מחשב נייד דק וקל עם מסך OLED 14 אינץ', מעבד Intel Core i7, 16GB RAM ו-1TB SSD. עם משטח מגע חכם ועיצוב יוקרתי.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/z/e/zenbook-14_ux3402va_refresh_product-photo_2s_ips_foggy-silver_14_numberpad_1_1_2_1_1.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/z/e/zenbook_14_ux3402va_refresh_product_photo_2s_ips_foggy_silver_06_numberpad_1_2_1_1.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/z/e/zenbook_14_ux3402va_refresh_product_photo_2s_ips_foggy_silver_08_numberpad_1_2_1_1.png",
    ],
    price: 4599,
    discount: 300,
    categories: ["computers"],
    amount: 14,
    rating: 4.2,
    reviews: 17,
    specifications: {
      processor: "Intel Core i7",
      ram: "16GB",
      storage: "1TB SSD",
      graphics_card: "משולב",
      operating_system: "Windows 11",
      connectivity_ports: ["USB-C", "USB 3.0", "HDMI"],
    },
  },
  {
    id: 2009,
    name: "מסך מקצועי דל 32 אינץ'",
    description:
      "מסך מקצועי למעצבים עם דיוק צבע מושלם, רזולוציית 4K, חיבור USB-C וטכנולוגיית מניעת הבהוב. כיסוי 100% של מרחב צבעים Adobe RGB.",
    images: [
      "https://pc-online.co.il/wp-content/uploads/2024/05/33100-1-3.webp",
      "https://pc-online.co.il/wp-content/uploads/2024/05/33100-2-2.webp",
      "https://pc-online.co.il/wp-content/uploads/2024/05/33100-3-1.webp",
    ],
    price: 3299,
    discount: 200,
    categories: ["computers", "accessories"],
    amount: 10,
    rating: 4.5,
    reviews: 11,
    specifications: {
      processor: null,
      ram: null,
      storage: null,
      graphics_card: null,
      operating_system: null,
      connectivity_ports: ["HDMI", "DisplayPort", "USB-C"],
      compatibility_accessory: ["מחשבי Windows", "מחשבי Mac"],
      material: "פלסטיק",
      connection_type: ["HDMI", "DisplayPort", "USB-C"],
      warranty: "שנתיים",
      color_options: "שחור",
      durability: "עמיד לשריטות",
    },
  },
  {
    id: 2010,
    name: "Mac Studio",
    description:
      "מחשב שולחני קומפקטי ורב עוצמה עם שבב M2 Ultra, 64GB RAM ו-2TB SSD. מיועד לעבודה מקצועית בעריכת וידאו, אנימציה ופיתוח.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/m/a/mac_studio_m2_pdp_image_position_7__wwen_background_remd_2_4.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/m/a/mac_studio_m2_pdp_image_position_2__wwen_background_roved_4.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/m/a/mac_studio_m2_pdp_image_position_6__wwen_background_rved_4.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/m/a/mac_studio_m2_pdp_image_position_4__wwen_2_1_5.jpg",
    ],
    price: 9999,
    discount: 0,
    categories: ["computers"],
    amount: 5,
    rating: 4.9,
    reviews: 15,
    specifications: {
      processor: "Apple M2",
      ram: "64GB",
      storage: "2TB SSD",
      graphics_card: "Apple GPU",
      operating_system: "macOS",
      connectivity_ports: ["USB-C", "Thunderbolt", "HDMI"],
    },
  },
  {
    id: 2011,
    name: "MSI GE76 Raider",
    description:
      "מחשב נייד גיימינג עם מעבד Intel Core i9, כרטיס מסך GeForce RTX 4090, 32GB RAM ו-2TB SSD. מסך 17.3 אינץ' עם קצב רענון 360Hz.",
    images: [
      "https://m.media-amazon.com/images/I/617fteEclkL._AC_SL1200_.jpg",
      "https://m.media-amazon.com/images/I/51XxTyN+H4L._AC_SL1200_.jpg",

      "https://m.media-amazon.com/images/I/51fSg+hwRbL._AC_SL1200_.jpg",
      "https://m.media-amazon.com/images/I/413upw2uiGL._AC_SL1200_.jpg",
    ],
    price: 11999,
    discount: 1000,
    categories: ["computers"],
    amount: 3,
    rating: 4.7,
    reviews: 8,
    specifications: {
      processor: "Intel Core i9",
      ram: "32GB",
      storage: "2TB SSD",
      graphics_card: "NVIDIA GeForce RTX",
      operating_system: "Windows 11",
      connectivity_ports: ["USB-C", "USB 3.0", "HDMI", "DisplayPort"],
    },
  },
  {
    id: 2012,
    name: "סמסונג Odyssey G9",
    description:
      "מסך גיימינג אולטרה-רחב 49 אינץ' בעיקול 1000R, רזולוציית DQHD וקצב רענון 240Hz. תמיכה ב-HDR1000 וחוויית משחק מושלמת.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/u/k/uk-odyssey-oled-g9-g93sd-ls49dg934suxxu-544376614.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/u/k/uk-odyssey-oled-g9-g93sd-ls49dg934suxxu-544376591.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/u/k/uk-odyssey-oled-g9-g93sd-ls49dg934suxxu-544376598.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/u/k/uk-odyssey-oled-g9-g93sd-ls49dg934suxxu-544376596.png",
    ],
    price: 4999,
    discount: 500,
    categories: ["computers", "accessories"],
    amount: 6,
    rating: 4.6,
    reviews: 12,
    specifications: {
      processor: null,
      ram: null,
      storage: null,
      graphics_card: null,
      operating_system: null,
      connectivity_ports: ["HDMI", "DisplayPort", "USB-C"],
      compatibility_accessory: ["מחשבי Windows", "מחשבי Mac"],
      material: "פלסטיק",
      connection_type: ["HDMI", "DisplayPort"],
      warranty: "שנתיים",
      color_options: "שחור",
      durability: "עמיד לשריטות",
    },
  },
  {
    id: 3001,
    name: "אייפון 15 Pro Max",
    description:
      "סמארטפון פרימיום עם מערכת צילום מתקדמת, מעבד A17 Pro, מסך 6.7 אינץ' Super Retina XDR ו-256GB אחסון. עמידות גבוהה למים ואבק.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/i/p/iphone_15_pro_max_natural_titanium_pdp_image_position-1__wwen_1.jpg",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/i/p/iphone_15_pro_max_natural_titanium_pdp_image_position-1_alt__wwen_1.jpg",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/i/p/iphone_15_pro_max_natural_titanium_pdp_image_position-2__wwen_1.jpg",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/i/p/iphone_15_pro_max_natural_titanium_pdp_image_position-3__wwen_1.jpg",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/i/p/iphone_15_pro_max_natural_titanium_pdp_image_position-4__wwen_1.jpg",
    ],
    price: 5499,
    discount: 200,
    categories: ["smartphones"],
    amount: 25,
    rating: 4.8,
    reviews: 26,
    specifications: {
      screen_size_phone: "6.7 אינץ'",
      camera: "מערך מצלמות משולש",
      battery_capacity: "4000mAh",
      storage_phone: "256GB",
      processor_phone: "Apple A-series",
      "5g_support": "כן",
    },
  },
  {
    id: 3002,
    name: "סמסונג גלקסי S24 Ultra",
    description:
      "סמארטפון מתקדם עם עט S Pen מובנה, מערך מצלמות מקצועי, מסך Dynamic AMOLED 2X בגודל 6.8 אינץ' ו-512GB אחסון. יכולות AI משולבות.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/s/m/sm-s928_galaxys24ultra_front_titaniumblack_231109_3.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/s/m/sm-s928_galaxys24ultra_devicepenfront_titaniumblack_231109_4.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/s/m/sm-s928_galaxys24ultra_devicepenfrontl30_titaniumblack_231109_4.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/s/m/sm-s928_galaxys24ultra_devicepenback_titaniumblack_231109_4.png",
    ],
    price: 5299,
    discount: 300,
    categories: ["smartphones"],
    amount: 18,
    rating: 4.7,
    reviews: 23,
    specifications: {
      screen_size_phone: "6.9 אינץ'",
      camera: "מערך מצלמות משולש",
      battery_capacity: "5000mAh",
      storage_phone: "512GB",
      processor_phone: "Exynos",
      "5g_support": "כן",
    },
  },
  {
    id: 3003,
    name: "שיאומי 14",
    description:
      "סמארטפון עם יחס מחיר-ביצועים מצוין, מצלמה ראשית 108MP, מעבד Snapdragon 8 Gen 2, מסך AMOLED 6.6 אינץ' וסוללה עוצמתית.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/r/e/redmi-note-14-black-1.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/r/e/redmi-note-14-black-2.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/r/e/redmi-note-14-black-5.png",
    ],
    price: 2899,
    discount: 300,
    categories: ["smartphones"],
    amount: 30,
    rating: 4.1,
    reviews: 19,
    specifications: {
      screen_size_phone: "6.5 אינץ'",
      camera: "108MP",
      battery_capacity: "5000mAh",
      storage_phone: "256GB",
      processor_phone: "Snapdragon",
      "5g_support": "כן",
    },
  },
  {
    id: 3004,
    name: "Google Pixel 8 Pro",
    description:
      "סמארטפון עם מצלמה מתקדמת ותוכנת עיבוד תמונה מהטובות בשוק. מעבד Tensor G3, 12GB RAM, מסך OLED 6.7 אינץ' וסוללה חזקה.",
    images: [
      "https://m.media-amazon.com/images/I/61aRO4jJM0L._AC_SL1000_.jpg",
      "https://m.media-amazon.com/images/I/51HKejvKV0L._AC_SL1000_.jpg",
      "https://m.media-amazon.com/images/I/61aRO4jJM0L._AC_SL1000_.jpg",
    ],
    price: 4499,
    discount: 400,
    categories: ["smartphones"],
    amount: 20,
    rating: 4.6,
    reviews: 17,
    specifications: {
      screen_size_phone: "6.7 אינץ'",
      camera: "מערך מצלמות משולש",
      battery_capacity: "5000mAh",
      storage_phone: "256GB",
      processor_phone: "Google Tensor",
      "5g_support": "כן",
    },
  },
  {
    id: 3005,
    name: "וואן פלוס 12",
    description:
      "סמארטפון פרימיום עם מסך Fluid AMOLED 6.7 אינץ', מעבד Snapdragon 8 Gen 3, מערך מצלמות Hasselblad וטעינה מהירה 100W.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/o/n/oneplus-13r-aston-gold-1.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/b/6/b60def72a25097d1075aa9ac84b92cb9.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/o/n/oneplus-13r-aston-gold-4.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/o/n/oneplus-13r-aston-gold-2.png",
    ],
    price: 3799,
    discount: 200,
    categories: ["smartphones"],
    amount: 15,
    rating: 4.3,
    reviews: 14,
    specifications: {
      screen_size_phone: "6.7 אינץ'",
      camera: "מערך מצלמות משולש",
      battery_capacity: "5000mAh",
      storage_phone: "256GB",
      processor_phone: "Snapdragon",
      "5g_support": "כן",
    },
  },
  {
    id: 3006,
    name: "סמסונג גלקסי Z Fold 5",
    description:
      "סמארטפון מתקפל עם מסך גמיש 7.6 אינץ' בפנים ומסך 6.2 אינץ' בחוץ. תמיכה ב-S Pen, מעבד Snapdragon 8 Gen 2 ו-512GB אחסון.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/s/m/sm-f956_zfold6_openback115_navy_240422_2.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/s/m/sm-f956_zfold6_openback_navy_240422_2.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/s/m/sm-f956_zfold6_openfront_navy_240422_2.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/s/m/sm-f956_zfold6_back_navy_240422_2.png",
    ],
    price: 7499,
    discount: 500,
    categories: ["smartphones"],
    amount: 10,
    rating: 4.4,
    reviews: 22,
    specifications: {
      screen_size_phone: "6.9 אינץ'",
      camera: "מערך מצלמות משולש",
      battery_capacity: "4000mAh",
      storage_phone: "512GB",
      processor_phone: "Snapdragon",
      "5g_support": "כן",
    },
  },
  {
    id: 3007,
    name: "אייפון SE (2024)",
    description:
      "סמארטפון אייפון במחיר נגיש עם מעבד A16 Bionic, מסך 4.7 אינץ' וכפתור בית עם Touch ID. מצלמה 12MP ו-128GB אחסון.",
    images: [
      "https://www.ivory.co.il/files/catalog/org/1742196189x89WG.webp",
      "https://www.ivory.co.il/files/catalog/org/1742196189o89TF.webp",
      "https://www.ivory.co.il/files/catalog/org/1742196189D89Ef.webp",
    ],
    price: 2499,
    discount: 0,
    categories: ["smartphones"],
    amount: 35,
    rating: 3.9,
    reviews: 27,
    specifications: {
      screen_size_phone: "5.5 אינץ'",
      camera: "12MP",
      battery_capacity: "3000mAh",
      storage_phone: "128GB",
      processor_phone: "Apple A-series",
      "5g_support": "כן",
    },
  },
  {
    id: 3008,
    name: "סמסונג גלקסי A54",
    description:
      "סמארטפון מבית סמסונג במחיר ביניים עם מצלמה משולשת 50MP, מסך Super AMOLED 6.4 אינץ', סוללה חזקה ו-128GB אחסון.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/s/m/sm-a546_galaxy-a54-5g_awesome-graphite_front.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/s/m/sm-a546_galaxy-a54-5g_awesome-graphite_front-r30.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/s/m/sm-a546_galaxy-a54-5g_awesome-graphite_back.png",
    ],
    price: 1699,
    discount: 200,
    categories: ["smartphones"],
    amount: 40,
    rating: 3.7,
    reviews: 18,
    specifications: {
      screen_size_phone: "6.5 אינץ'",
      camera: "מערך מצלמות משולש",
      battery_capacity: "5000mAh",
      storage_phone: "128GB",
      processor_phone: "Exynos",
      "5g_support": "כן",
    },
  },
  {
    id: 3009,
    name: "מוטורולה Edge 50 Ultra",
    description:
      "סמארטפון פרימיום עם מסך עקום OLED 6.7 אינץ', מצלמה 200MP, מעבד Snapdragon 8+ Gen 2 וטעינה אלחוטית מהירה.",
    images: ["https://m.media-amazon.com/images/I/71qH6tjkjSL._AC_SL1500_.jpg"],
    price: 3299,
    discount: 300,
    categories: ["smartphones"],
    amount: 12,
    rating: 4.0,
    reviews: 11,
    specifications: {
      screen_size_phone: "6.7 אינץ'",
      camera: "200MP",
      battery_capacity: "4000mAh",
      storage_phone: "256GB",
      processor_phone: "Snapdragon",
      "5g_support": "כן",
    },
  },
  {
    id: 4001,
    name: "אוזניות אפל AirPods Pro 2",
    description:
      "אוזניות אלחוטיות עם ביטול רעשים אקטיבי, איכות שמע מעולה, חיי סוללה ארוכים ועמידות בפני זיעה ומים. תמיכה ב-Spatial Audio.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/f/i/file_86_1_1_1_1.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/a/i/airpods_pro_2nd_gen_pdp_image_position-3__wwen_1_2_1_1.jpg",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/a/i/airpods_pro_2nd_gen_pdp_image_position-1__wwen_1_2_1_1.jpg",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/a/i/airpods_pro_2nd_gen_pdp_image_position-5__wwen_1_2_1_1.jpg",
    ],
    price: 999,
    discount: 100,
    categories: ["audio", "accessories"],
    amount: 40,
    rating: 4.5,
    reviews: 25,
    specifications: {
      power_output: "10W",
      connectivity_audio: ["Bluetooth", "אלחוטי"],
      battery_life_audio: "עד 5 שעות",
      sound_quality: "Hi-Fi",
      noise_cancellation: "אקטיבי (ANC)",
      waterproof_rating_audio: "IPX4",
      compatibility_accessory: "iPhone",
      material: "פלסטיק",
      connection_type: "אלחוטי",
      warranty: "שנה",
      color_options: "לבן",
      durability: "עמיד למים",
    },
  },
  {
    id: 4002,
    name: "רמקול חכם סונוס One",
    description:
      "רמקול חכם עם איכות שמע יוצאת דופן, תמיכה ב-Alexa ו-Google Assistant, יכולת חיבור למערכות סאונד נוספות ועיצוב אלגנטי.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/g/v/gvhgfg.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/v/b/vbnvbnvb.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/v/b/vbnvgh.png",
    ],
    price: 899,
    discount: 0,
    categories: ["audio", "gadgets"],
    amount: 15,
    rating: 4.3,
    reviews: 16,
    specifications: {
      power_output: "50W",
      connectivity_audio: ["WiFi", "Bluetooth", "אלחוטי"],
      battery_life_audio: "חיבור לחשמל בלבד",
      sound_quality: "סטריאו",
      noise_cancellation: "אין",
      waterproof_rating_audio: "אין",
      battery_life_gadget: "חיבור לחשמל בלבד",
      compatibility_gadget: "תאימות עם כל המכשירים",
      sensors: null,
      connectivity_gadget: ["WiFi", "Bluetooth"],
      water_resistance: "לא עמיד למים",
      special_features: "שליטה בבית חכם",
    },
  },
  {
    id: 4003,
    name: "מערכת קולנוע ביתית בוז Soundbar 700",
    description:
      "סאונדבר פרימיום עם איכות שמע עשירה, באס עמוק, תמיכה ב-Dolby Atmos ו-DTS:X. כולל שלט חכם ואפשרויות חיבור מתקדמות.",
    images: [
      "https://m.media-amazon.com/images/I/51P+sQAS5iL._AC_SL1200_.jpg",
      "https://m.media-amazon.com/images/I/51KETyTkxVL._AC_SL1200_.jpg",
      "https://m.media-amazon.com/images/I/61UZlD7qIdL._AC_SL1200_.jpg",
      "https://m.media-amazon.com/images/I/511ibJEw4aL._AC_SL1200_.jpg",
    ],
    price: 3499,
    discount: 200,
    categories: ["audio"],
    amount: 8,
    rating: 4.4,
    reviews: 13,
    specifications: {
      power_output: "100W",
      connectivity_audio: ["HDMI", "WiFi", "Bluetooth", "אלחוטי"],
      battery_life_audio: "חיבור לחשמל בלבד",
      sound_quality: "Dolby Atmos",
      noise_cancellation: "אין",
      waterproof_rating_audio: "אין",
    },
  },
  {
    id: 4004,
    name: "אוזניות סוני WH-1000XM5",
    description:
      "אוזניות Over-Ear עם ביטול רעשים מוביל בתעשייה, איכות שמע Hi-Res, מיקרופונים משופרים לשיחות נקיות וחיי סוללה של עד 30 שעות.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/w/h/wh-1000xm5bk_main_1.jpg",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/w/h/wh-1000xm5bk_main_2.jpg",

      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/w/h/wh-1000xm5bk_main_4.jpg",
    ],
    price: 1499,
    discount: 150,
    categories: ["audio", "accessories"],
    amount: 22,
    rating: 4.7,
    reviews: 24,
    specifications: {
      power_output: "10W",
      connectivity_audio: ["Bluetooth", "אלחוטי"],
      battery_life_audio: "עד 30 שעות",
      sound_quality: "Hi-Fi",
      noise_cancellation: "אקטיבי (ANC)",
      waterproof_rating_audio: "אין",
      compatibility_accessory: "כל המכשירים",
      material: "פלסטיק",
      connection_type: "Bluetooth",
      warranty: "שנתיים",
      color_options: "שחור",
      durability: "עמיד לשריטות",
    },
  },
  {
    id: 4005,
    name: "JBL Flip 6",
    description:
      "רמקול נייד עמיד במים עם סוללה ל-12 שעות, צליל סטריאו איכותי וחיבור Bluetooth מתקדם. אפשרות לחיבור מספר רמקולים יחד.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/eilat.payngo.co.il/media/catalog/product/3/_/3_jbl_flip6_front_black_29509_x2.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/eilat.payngo.co.il/media/catalog/product/2/_/2_jbl_flip6_3_4_right_black_30195_x1.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/eilat.payngo.co.il/media/catalog/product/4/_/4_jbl_flip6_right_black_29529_x2.png",
    ],
    price: 549,
    discount: 50,
    categories: ["audio"],
    amount: 30,
    rating: 4.2,
    reviews: 20,
    specifications: {
      power_output: "20W",
      connectivity_audio: ["Bluetooth", "אלחוטי"],
      battery_life_audio: "עד 10 שעות",
      sound_quality: "סטריאו",
      noise_cancellation: "אין",
      waterproof_rating_audio: "IPX7",
    },
  },
  {
    id: 4006,
    name: "Sennheiser Momentum 4 Wireless",
    description:
      "אוזניות פרימיום עם ביטול רעשים מתקדם, סוללה ל-60 שעות, איכות שמע גבוהה במיוחד ונוחות לשימוש ממושך.",
    images: [
      "https://m.media-amazon.com/images/I/71zsm84mJsL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71u8h5wCTfL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/81wIQ-xZ6VL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71InN2EJgQL._AC_SL1500_.jpg",
    ],
    price: 1399,
    discount: 200,
    categories: ["audio", "accessories"],
    amount: 15,
    rating: 4.6,
    reviews: 18,
    specifications: {
      power_output: "10W",
      connectivity_audio: ["Bluetooth", "אלחוטי"],
      battery_life_audio: "עד 30 שעות",
      sound_quality: "Hi-Fi",
      noise_cancellation: "אקטיבי (ANC)",
      waterproof_rating_audio: "אין",
      compatibility_accessory: "כל המכשירים",
      material: "פלסטיק",
      connection_type: "Bluetooth",
      warranty: "שנתיים",
      color_options: "שחור",
      durability: "עמיד לשריטות",
    },
  },
  {
    id: 4007,
    name: "מגבר סטריאו ביתי Yamaha",
    description:
      "מגבר סטריאו איכותי עם 100W לערוץ, חיבורי HDMI, Bluetooth, ותמיכה בסטרימינג ישיר. בקרת טון מתקדמת לשמע מאוזן.",
    images: [
      "https://d3m9l0v76dty0.cloudfront.net/system/photos/1232586/extra_large/2e163c2619403b3dddbb0d6579c66fb3.jpg",
      "https://d3m9l0v76dty0.cloudfront.net/system/photos/1232588/extra_large/d6e7db369a32ae7bf66d70f4c952cdd7.jpg",
    ],
    price: 2299,
    discount: 200,
    categories: ["audio"],
    amount: 10,
    rating: 4.3,
    reviews: 12,
    specifications: {
      power_output: "100W",
      connectivity_audio: ["HDMI", "Bluetooth", "WiFi"],
      battery_life_audio: "חיבור לחשמל בלבד",
      sound_quality: "Hi-Fi",
      noise_cancellation: "אין",
      waterproof_rating_audio: "אין",
    },
  },
  {
    id: 4008,
    name: "אוזניות גיימינג HyperX Cloud Alpha",
    description:
      "אוזניות גיימינג עם מיקרופון נשלף, סאונד סטריאו 7.1 וירטואלי, רמקולים כפולים וכריות זיכרון נוחות לשימוש ממושך.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/n/e/new_44444.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/n/e/new_proj343ect.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/n/e/new_pr_333_oject.png",
    ],
    price: 399,
    discount: 0,
    categories: ["audio", "accessories"],
    amount: 28,
    rating: 4.1,
    reviews: 17,
    specifications: {
      power_output: "10W",
      connectivity_audio: ["חוטי"],
      battery_life_audio: "חיבור לחשמל בלבד",
      sound_quality: "סראונד",
      noise_cancellation: "פסיבי",
      waterproof_rating_audio: "אין",
      compatibility_accessory: ["מחשבי Windows", "מחשבי Mac"],
      material: "פלסטיק",
      connection_type: "USB-A",
      warranty: "שנתיים",
      color_options: "שחור",
      durability: "עמיד לשריטות",
    },
  },
  {
    id: 4009,
    name: "מערכת רמקולים 5.1 Logitech",
    description:
      "מערכת רמקולים 5.1 לחווית קולנוע ביתית עם סאבוופר עוצמתי, רמקולים לווייניים איכותיים ושלט לשליטה מרחוק.",
    images: [
      "https://www.ivory.co.il/files/catalog/org/1593084882z82Lo.jpg",
      "https://www.ivory.co.il/files/catalog/org/1593084882c82Dr.jpg",
      "https://www.ivory.co.il/files/catalog/org/1593084883f83QP.jpg",
      "https://www.ivory.co.il/files/catalog/org/1593084883x83PH.jpg",
    ],
    price: 999,
    discount: 0,
    categories: ["audio"],
    amount: 14,
    rating: 3.9,
    reviews: 11,
    specifications: {
      power_output: "200W+",
      connectivity_audio: ["חוטי", "AUX"],
      battery_life_audio: "חיבור לחשמל בלבד",
      sound_quality: "סראונד",
      noise_cancellation: "אין",
      waterproof_rating_audio: "אין",
    },
  },
  {
    id: 5001,
    name: "אפל ווטש סדרה 9",
    description:
      "שעון חכם עם מסך Retina תמידי, מעקב בריאות מתקדם, GPS מובנה, עמידות במים ומגוון רצועות להחלפה. תומך ב-Apple Pay.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/a/p/apple_watch_series_9_gps_41mm_silver_aluminum_storm_blue_sport_band_pdp_image_position-2__wwen_1_1.jpg",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/a/p/apple_watch_series_9_gps_41mm_silver_aluminum_storm_blue_sport_band_pdp_image_position-1__wwen_1_1.jpg",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/a/p/apple_watch_series_9_gps_41mm_silver_aluminum_storm_blue_sport_band_pdp_image_position-3__wwen_1_1.jpg",
    ],
    price: 1899,
    discount: 200,
    categories: ["gadgets", "accessories"],
    amount: 25,
    rating: 4.7,
    reviews: 21,
    specifications: {
      battery_life_gadget: "עד 3 ימים",
      compatibility_gadget: "iOS",
      sensors: ["דופק", "GPS", "מד צעדים", "מד חמצן בדם", "מד שינה"],
      connectivity_gadget: ["Bluetooth", "WiFi", "NFC"],
      water_resistance: "עמיד למים עד 30 מטר",
      special_features: ["מעקב כושר", "ניטור בריאות", "תמיכה בתשלומים"],
      compatibility_accessory: "iPhone",
      material: "אלומיניום",
      connection_type: "אלחוטי",
      warranty: "שנה",
      color_options: "מגוון צבעים",
      durability: ["עמיד למים", "עמיד לאבק"],
    },
  },
  {
    id: 5002,
    name: "אוקולוס קווסט 3",
    description:
      "מערכת מציאות מדומה עצמאית עם רזולוציה גבוהה, בקרי מגע מתקדמים, מעקב תנועה משופר וספריית משחקים ואפליקציות עשירה.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/m/e/meta_quest_3s_1_.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/m/e/meta_quest_3s_2_.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/m/e/meta_quest_3s_3_.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/m/e/meta_quest_3s_5_.png",
    ],
    price: 2499,
    discount: 0,
    categories: ["gadgets"],
    amount: 10,
    rating: 4.5,
    reviews: 16,
    specifications: {
      battery_life_gadget: "עד יום",
      compatibility_gadget: "תאימות עם כל המכשירים",
      sensors: null,
      connectivity_gadget: ["Bluetooth", "WiFi"],
      water_resistance: "לא עמיד למים",
      special_features: "מציאות מדומה",
    },
  },
  {
    id: 5003,
    name: "צמיד כושר פיטביט צ'ארג' 6",
    description:
      "צמיד כושר עם מסך צבעוני, מעקב דופק מתמשך, מעקב שינה, GPS מובנה וחיי סוללה של עד 7 ימים. עמיד במים עד 50 מטר.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/v/i/vivosmart5_black_front.jpg",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/v/i/vivosmart5_black_main.jpg",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/v/i/vivosmart5_black_back.jpg",
    ],
    price: 799,
    discount: 100,
    categories: ["gadgets", "accessories"],
    amount: 35,
    rating: 4.0,
    reviews: 19,
    specifications: {
      battery_life_gadget: "עד שבוע",
      compatibility_gadget: ["Android", "iOS"],
      sensors: ["דופק", "GPS", "מד צעדים", "מד שינה"],
      connectivity_gadget: "Bluetooth",
      water_resistance: "עמיד למים עד 30 מטר",
      special_features: ["מעקב כושר", "ניטור בריאות"],
      compatibility_accessory: "כל המכשירים",
      material: "סיליקון",
      connection_type: "אלחוטי",
      warranty: "שנה",
      color_options: "מגוון צבעים",
      durability: "עמיד למים",
    },
  },
  {
    id: 5004,
    name: "גארמין Fenix 7",
    description:
      "שעון ספורט מתקדם עם ניטור דופק, מעקב אחר פעילויות מרובות, מפות מובנות וסוללה שמחזיקה עד 18 ימים. עיצוב חזק ועמיד במיוחד.",
    images: [
      "https://i.ebayimg.com/images/g/IE8AAOSwcRpnF--A/s-l960.webp",
      "https://i.ebayimg.com/images/g/iVUAAOSwGjlnF--A/s-l1600.webp",

      "https://i.ebayimg.com/images/g/KM8AAOSwmolnF--B/s-l1600.webp",
      "https://i.ebayimg.com/images/g/I1wAAOSw805nF--B/s-l1600.webp",
    ],
    price: 2999,
    discount: 300,
    categories: ["gadgets", "accessories"],
    amount: 12,
    rating: 4.8,
    reviews: 14,
    specifications: {
      battery_life_gadget: "עד שבועיים",
      compatibility_gadget: ["Android", "iOS"],
      sensors: ["דופק", "GPS", "מד צעדים", "מד חמצן בדם", "מד שינה"],
      connectivity_gadget: ["Bluetooth", "WiFi"],
      water_resistance: "עמיד למים עד 30 מטר",
      special_features: ["מעקב כושר", "ניטור בריאות"],
      compatibility_accessory: "כל המכשירים",
      material: "מתכת",
      connection_type: "אלחוטי",
      warranty: "שנתיים",
      color_options: "שחור",
      durability: ["עמיד לנפילות", "עמיד למים", "עמיד לאבק"],
    },
  },
  {
    id: 5005,
    name: "DJI Mini 3 Pro",
    description:
      "רחפן קומפקטי במשקל פחות מ-250 גרם עם מצלמה 4K, זמן טיסה של 34 דקות, יכולות צילום מתקדמות וטכנולוגיות מניעת התנגשויות.",
    images: [
      "https://m.media-amazon.com/images/I/61Y1P6uIRFL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61NGdIO3fAL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71F1vMQUZ6L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61AxhChIz3L._AC_SL1500_.jpg",
    ],
    price: 3499,
    discount: 300,
    categories: ["gadgets"],
    amount: 8,
    rating: 4.6,
    reviews: 10,
    specifications: {
      battery_life_gadget: "עד יום",
      compatibility_gadget: ["Android", "iOS"],
      sensors: ["GPS"],
      connectivity_gadget: ["WiFi", "Bluetooth"],
      water_resistance: "לא עמיד למים",
      special_features: null,
    },
  },
  {
    id: 5006,
    name: "סמסונג גלקסי Watch 6 Classic",
    description:
      "שעון חכם עם מסך AMOLED מרהיב, מעקב בריאות מתקדם, אפשרויות תשלום מובנות וחיי סוללה ארוכים. עיצוב קלאסי עם חוגה מסתובבת.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/eilat.payngo.co.il/media/catalog/product/s/m/sm-r950_001_front_black.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/eilat.payngo.co.il/media/catalog/product/s/m/sm-r950_002_front2_black.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/eilat.payngo.co.il/media/catalog/product/s/m/sm-r950_003_l-perspective_black.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/eilat.payngo.co.il/media/catalog/product/y/-/y-watch6-classic-r955-sm-r950nzkailo-5374.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/eilat.payngo.co.il/media/catalog/product/s/m/sm-r955_006_front3_black.png",
    ],
    price: 1599,
    discount: 200,
    categories: ["gadgets", "accessories"],
    amount: 18,
    rating: 4.4,
    reviews: 17,
    specifications: {
      battery_life_gadget: "עד 3 ימים",
      compatibility_gadget: "Android",
      sensors: ["דופק", "GPS", "מד צעדים", "מד חמצן בדם", "מד שינה"],
      connectivity_gadget: ["Bluetooth", "WiFi", "NFC"],
      water_resistance: "עמיד למים עד 30 מטר",
      special_features: ["מעקב כושר", "ניטור בריאות", "תמיכה בתשלומים"],
      compatibility_accessory: "Android",
      material: "מתכת",
      connection_type: "אלחוטי",
      warranty: "שנה",
      color_options: ["שחור", "כסף"],
      durability: ["עמיד למים", "עמיד לאבק"],
    },
  },
  {
    id: 5007,
    name: "אמזון Echo Show 10",
    description:
      "רמקול חכם עם מסך מגע 10.1 אינץ' שמסתובב אוטומטית לכיוון המשתמש. עם Alexa מובנה, מצלמה HD, מיקרופונים מתקדמים ורמקולים עוצמתיים.",
    images: [
      "https://i0.wp.com/www.cwc.co.il/wp-content/uploads/2023/02/10.png?w=711&ssl=1",
      "https://i0.wp.com/www.cwc.co.il/wp-content/uploads/2023/02/100.png?w=690&ssl=1",
    ],
    price: 1299,
    discount: 150,
    categories: ["gadgets", "audio"],
    amount: 14,
    rating: 4.2,
    reviews: 13,
    specifications: {
      battery_life_gadget: "חיבור לחשמל בלבד",
      compatibility_gadget: "תאימות עם כל המכשירים",
      sensors: null,
      connectivity_gadget: ["WiFi", "Bluetooth"],
      water_resistance: "לא עמיד למים",
      special_features: "שליטה בבית חכם",
      power_output: "50W",
      connectivity_audio: ["WiFi", "Bluetooth"],
      battery_life_audio: "חיבור לחשמל בלבד",
      sound_quality: "סטריאו",
      noise_cancellation: "אין",
      waterproof_rating_audio: "אין",
    },
  },
  {
    id: 5008,
    name: "DJI Osmo Mobile 6",
    description:
      "מייצב סמארטפונים חכם עם מנועים חזקים, מעקב אוטומטי אחר נושאים, מצבי צילום מתקדמים וקיפול קומפקטי לניידות מקסימלית.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/eilat.payngo.co.il/media/catalog/product/o/s/osmo_mobile_6_1__1.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/eilat.payngo.co.il/media/catalog/product/o/s/osmo_mobile_6_3__1.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/eilat.payngo.co.il/media/catalog/product/o/s/osmo_mobile_6_4__1.png",
    ],
    price: 699,
    discount: 100,
    categories: ["gadgets", "accessories"],
    amount: 22,
    rating: 4.1,
    reviews: 15,
    specifications: {
      battery_life_gadget: "עד יום",
      compatibility_gadget: ["Android", "iOS"],
      sensors: null,
      connectivity_gadget: "Bluetooth",
      water_resistance: "לא עמיד למים",
      special_features: null,
      compatibility_accessory: ["iPhone", "Android"],
      material: "פלסטיק",
      connection_type: "Bluetooth",
      warranty: "שנה",
      color_options: "שחור",
      durability: "עמיד לשריטות",
    },
  },
  {
    id: 5009,
    name: "אייפד Pro M2",
    description:
      "טאבלט מתקדם עם שבב M2, מסך Liquid Retina XDR 12.9 אינץ', 256GB אחסון ותמיכה ב-Apple Pencil 2. מושלם לעבודה יצירתית וצריכת מדיה.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/i/p/ipad_pro_13-inch_m4_chip_wi-fi_silver_2-up_print__usen_5_3.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/i/p/ipad_pro_13_m4_wifi_silver_pdp_image_position_1a__wwen_5_3.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/i/p/ipad_pro_13_m4_wifi_silver_pdp_image_position_3__wwen_5_3.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/i/p/ipad_pro_13_m4_wifi_silver_pdp_image_position_2__wwen_5_3.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/i/p/ipad_pro_13_m4_wifi_silver_pdp_image_position_4__wwen_4_3.jpg",
    ],
    price: 4999,
    discount: 400,
    categories: ["gadgets", "computers"],
    amount: 15,
    rating: 4.9,
    reviews: 20,
    specifications: {
      battery_life_gadget: "עד יום",
      compatibility_gadget: "iOS",
      sensors: null,
      connectivity_gadget: ["WiFi", "Bluetooth"],
      water_resistance: "לא עמיד למים",
      special_features: null,
      processor: "Apple M2",
      ram: "16GB",
      storage: "256GB SSD",
      graphics_card: "Apple GPU",
      operating_system: "iPadOS",
      connectivity_ports: ["USB-C", "Thunderbolt"],
    },
  },
  {
    id: 6001,
    name: "מטען אלחוטי מגנטי אנקר",
    description:
      "מטען אלחוטי מהיר עם טכנולוגיה מגנטית, תאימות מלאה למכשירי אייפון עם MagSafe וטעינה מהירה למכשירי אנדרואיד תומכים.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/d/9/d92714bf-18de-4a5f-9e5e-13cd24c0460a_copy.jpg",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/f/1/f1f217f7-976f-4b6c-b5b8-941a877518d4.jpg",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/7/f/7fdbfba4-23f4-45cb-9027-b661b9d6e441.jpg",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/4/d/4db44bd9-99f8-4136-8e88-5a3a97170a10.jpg",
    ],
    price: 199,
    discount: 0,
    categories: ["accessories"],
    amount: 50,
    rating: 4.3,
    reviews: 23,
    specifications: {
      compatibility_accessory: ["iPhone", "Android"],
      material: "פלסטיק",
      connection_type: "אלחוטי",
      warranty: "שנה",
      color_options: "שחור",
      durability: "עמיד לשריטות",
    },
  },
  {
    id: 6002,
    name: "סוללת גיבוי RAVPower 26800mAh",
    description:
      "סוללת גיבוי עוצמתית עם קיבולת גבוהה, יציאות USB מרובות, טעינה מהירה PD וטכנולוגיית iSmart לטעינה אופטימלית.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/8/b/8b30852e-f4f8-4075-b48f-79492c64c60b.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/2/6/26544b08-3b46-45fa-8118-9e6687d9eff7.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/4/2/42a00ddf-5bc2-4660-a32a-11ce60e44cf0.png",
    ],
    price: 249,
    discount: 50,
    categories: ["accessories"],
    amount: 45,
    rating: 4.2,
    reviews: 26,
    specifications: {
      compatibility_accessory: "כל המכשירים",
      material: "פלסטיק",
      connection_type: ["USB-A", "USB-C"],
      warranty: "שנה",
      color_options: "שחור",
      durability: "עמיד לנפילות",
    },
  },
  {
    id: 6003,
    name: "כבל USB-C ל-Lightning בלקין",
    description:
      "כבל באיכות גבוהה עם אישור MFi של אפל, אורך 2 מטר, חומרים עמידים ותמיכה בטעינה מהירה עד 20W. מתאים לכל מכשירי אפל.",
    images: [
      "https://d3m9l0v76dty0.cloudfront.net/system/photos/13698989/large/c60002d5d499299c6dfc00810a72aaba.png",
    ],
    price: 129,
    discount: 20,
    categories: ["accessories"],
    amount: 100,
    rating: 3.9,
    reviews: 24,
    specifications: {
      compatibility_accessory: "iPhone",
      material: "סיליקון",
      connection_type: ["USB-C", "Lightning"],
      warranty: "שנתיים",
      color_options: "שחור",
      durability: "עמיד לשריטות",
    },
  },
  {
    id: 6004,
    name: "מטען קיר Anker Nano II 65W",
    description:
      "מטען קיר קומפקטי עם טכנולוגיית GaN II, הספק 65W, יציאת USB-C ותמיכה בטעינה מהירה למגוון מכשירים כולל מחשבים ניידים.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/6/1/61prvw0fydl._ac_sl1500_.png",
    ],
    price: 179,
    discount: 30,
    categories: ["accessories"],
    amount: 60,
    rating: 4.4,
    reviews: 21,
    specifications: {
      compatibility_accessory: "כל המכשירים",
      material: "פלסטיק",
      connection_type: "USB-C",
      warranty: "שנה",
      color_options: "לבן",
      durability: "עמיד לחום",
    },
  },
  {
    id: 6005,
    name: "מגן מסך לאייפון Spigen",
    description:
      "מגן מסך זכוכית מחוסמת עם דיוק התקנה גבוה, ציפוי נגד טביעות אצבע, עמידות גבוהה בפני שריטות וחבילה הכוללת 2 יחידות.",
    images: [
      "https://m.media-amazon.com/images/I/61y8cbgj+TL._AC_SL1200_.jpg",
      "https://m.media-amazon.com/images/I/61P0VIdKwBL._AC_SL1200_.jpg",
    ],
    price: 89,
    discount: 0,
    categories: ["accessories"],
    amount: 150,
    rating: 4.0,
    reviews: 27,
    specifications: {
      compatibility_accessory: "iPhone",
      material: "זכוכית מחוסמת",
      connection_type: null,
      warranty: "שנה",
      color_options: "שקוף",
      durability: "עמיד לשריטות",
    },
  },
  {
    id: 6006,
    name: "תיק נשיאה למחשב נייד Targus",
    description:
      "תיק איכותי למחשבים ניידים עד 15.6 אינץ', עם תאים רבים לאחסון, גב מרופד, רצועת כתף מתכווננת וחומרים עמידים במים.",
    images: [
      "https://www.tik4u.co.il/wp-content/uploads/2023/06/SW600648_12022022114435.png",
      "https://www.tik4u.co.il/wp-content/uploads/2023/06/SW600648_12022022114515-595x530.jpg",
      "https://www.tik4u.co.il/wp-content/uploads/2023/06/SW600648_12022022114507-595x503.jpg",
    ],
    price: 249,
    discount: 50,
    categories: ["accessories"],
    amount: 35,
    rating: 3.8,
    reviews: 19,
    specifications: {
      compatibility_accessory: ["מחשבי Windows", "מחשבי Mac"],
      material: "בד",
      connection_type: null,
      warranty: "שנה",
      color_options: "שחור",
      durability: ["עמיד למים", "עמיד לשריטות"],
    },
  },
  {
    id: 6007,
    name: "עכבר גיימינג Logitech G502 HERO",
    description:
      "עכבר גיימינג עם חיישן אופטי 25K DPI, 11 לחצנים הניתנים לתכנות, משקולות מותאמות אישית ותאורת RGB מתקדמת.",
    images: [
      "https://www.ivory.co.il/files/catalog/org/1730643556a56VN.webp",
      "https://www.ivory.co.il/files/catalog/org/1730643556C56Nl.webp",
      "https://www.ivory.co.il/files/catalog/org/1730643556p56YJ.webp",
      "https://www.ivory.co.il/files/catalog/org/1730643556v56Qk.webp",
    ],
    price: 349,
    discount: 50,
    categories: ["accessories", "computers"],
    amount: 25,
    rating: 4.8,
    reviews: 25,
    specifications: {
      compatibility_accessory: ["מחשבי Windows", "מחשבי Mac"],
      material: "פלסטיק",
      connection_type: "USB-A",
      warranty: "שנתיים",
      color_options: "שחור",
      durability: "עמיד לשריטות",
      processor: null,
      ram: null,
      storage: null,
      graphics_card: null,
      operating_system: null,
      connectivity_ports: null,
    },
  },
  {
    id: 6008,
    name: "מקלדת מכנית Keychron K8",
    description:
      "מקלדת מכנית אלחוטית עם חיבור Bluetooth, תאורת RGB, מתגים חליפיים, פריסה של 87 מקשים ותאימות למערכות הפעלה מרובות.",
    images: [
      "https://m.media-amazon.com/images/I/61SNg63eqgL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/917ABoS7e9L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71hqQZwBDbL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/51oAbtx1cNL._AC_SL1000_.jpg",
    ],
    price: 499,
    discount: 0,
    categories: ["accessories", "computers"],
    amount: 18,
    rating: 4.5,
    reviews: 16,
    specifications: {
      compatibility_accessory: ["מחשבי Windows", "מחשבי Mac"],
      material: "אלומיניום",
      connection_type: ["Bluetooth", "USB-C"],
      warranty: "שנה",
      color_options: "שחור",
      durability: "עמיד לשריטות",
      processor: null,
      ram: null,
      storage: null,
      graphics_card: null,
      operating_system: null,
      connectivity_ports: null,
    },
  },
  {
    id: 6009,
    name: "משטח טעינה אלחוטי Belkin 3 ב-1",
    description:
      "משטח טעינה אלחוטי לטעינה בו-זמנית של אייפון, אפל ווטש ו-AirPods. עיצוב אלגנטי, טעינה מהירה ומעמד צפייה מובנה.",
    images: [
      "https://d3m9l0v76dty0.cloudfront.net/system/photos/13051892/extra_large/ccd24c72a83e3473c16680f7af5e4a5f.jpg",
      "https://d3m9l0v76dty0.cloudfront.net/system/photos/13051893/large/ef53afa5a5e1fd5a512685b451317129.jpg",
      "https://d3m9l0v76dty0.cloudfront.net/system/photos/13051895/large/3b8c0ea28f233054b86ef3a0d4321e75.jpg",
    ],
    price: 599,
    discount: 100,
    categories: ["accessories"],
    amount: 12,
    rating: 4.6,
    reviews: 14,
    specifications: {
      compatibility_accessory: "iPhone",
      material: "פלסטיק",
      connection_type: "אלחוטי",
      warranty: "שנתיים",
      color_options: "לבן",
      durability: "עמיד לשריטות",
    },
  },
  {
    id: 6010,
    name: "כיסוי מגן לאייפון Spigen Ultra Hybrid",
    description:
      "כיסוי שקוף עם גב אחורי קשיח ומסגרת גמישה, הגנה מתקדמת מפני נפילות, עיצוב דק במיוחד וגישה קלה לכל הכפתורים.",
    images: [
      "https://shipi.b-cdn.net/wp-content/uploads/2024/09/%D7%9B%D7%99%D7%A1%D7%95%D7%99-%D7%A9%D7%A7%D7%95%D7%A3-%D7%93%D7%A7-%D7%9C%D7%90%D7%99%D7%99%D7%A4%D7%95%D7%9F-16-%D7%A4%D7%A8%D7%95-%D7%AA%D7%95%D7%9E%D7%9A-%D7%98%D7%A2%D7%99%D7%A0%D7%AA-MagSafe-%D7%90%D7%9C%D7%97%D7%95%D7%98%D7%99%D7%AA-Grip-Case-Crystal-1.png",
    ],
    price: 149,
    discount: 30,
    categories: ["accessories"],
    amount: 80,
    rating: 3.9,
    reviews: 22,
    specifications: {
      compatibility_accessory: "iPhone",
      material: "סיליקון",
      connection_type: null,
      warranty: "שנה",
      color_options: "שקוף",
      durability: ["עמיד לנפילות", "עמיד לשריטות"],
    },
  },
  {
    id: 6011,
    name: "רפידות קירור למחשב נייד Havit",
    description:
      "משטח קירור עם 3 מאווררים חזקים, תאורת RGB, 6 מצבי גובה מתכווננים וחיבור USB. מתאים למחשבים ניידים עד 17 אינץ'.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/g/x/gxf0x02619-560x450-02.ceb97ef4fad128ac_copy.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/g/x/gxf0x02619-560x450-03.7b436f6630de51e5_copy.png",
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/g/x/gxf0x02619-560x450-04.a2ddfbce128d3ec6_copy.png",
    ],
    price: 169,
    discount: 30,
    categories: ["accessories", "computers"],
    amount: 25,
    rating: 3.7,
    reviews: 18,
    specifications: {
      compatibility_accessory: ["מחשבי Windows", "מחשבי Mac"],
      material: "פלסטיק",
      connection_type: "USB-A",
      warranty: "שנה",
      color_options: "שחור",
      durability: "עמיד לשריטות",
      processor: null,
      ram: null,
      storage: null,
      graphics_card: null,
      operating_system: null,
      connectivity_ports: null,
    },
  },
  {
    id: 6012,
    name: "תחנת עגינה Anker 12 ב-1",
    description:
      "תחנת עגינה מתקדמת עם חיבורי HDMI, USB-A, USB-C, קורא כרטיסים, יציאת אודיו ויציאת רשת. תומכת בטעינה מהירה עד 100W.",
    images: [
      "https://d2d22nphq0yz8t.cloudfront.net/6cbcadef-96e0-49e9-b3bd-9921afe362db/www.payngo.co.il/media/catalog/product/3/d/3d135e1a-f6e3-4038-bad2-3c973d4671df.png",
    ],
    price: 599,
    discount: 0,
    categories: ["accessories", "computers"],
    amount: 15,
    rating: 4.4,
    reviews: 13,
    specifications: {
      compatibility_accessory: ["מחשבי Windows", "מחשבי Mac"],
      material: "אלומיניום",
      connection_type: ["HDMI", "USB-A", "USB-C"],
      warranty: "שנתיים",
      color_options: "כסף",
      durability: "עמיד לשריטות",
      processor: null,
      ram: null,
      storage: null,
      graphics_card: null,
      operating_system: null,
      connectivity_ports: ["USB-C", "USB 3.0", "HDMI", "DisplayPort"],
    },
  },
];
